import { createSlice } from '@reduxjs/toolkit';
import { Chance } from 'chance';
import type { PayloadAction } from '@reduxjs/toolkit';
import axios from '../../../utils/axios';
import { AppDispatch } from '@/store/Store';

const API_URL = '/api/data/contacts/ContactsData';

const chance = new Chance();

interface StateType {
  contacts: any[];
  contactContent: number;
  contactSearch: string;
  editContact: boolean;
  currentFilter: string;
}

const initialState = {
  contacts: [
    {
      id: 1,
      firstname: 'Barbara',
      lastname: 'Rangel',
      image: 'user1',
      department: 'Support',
      company: 'Robinson LLC',
      phone: '045-377-4202',
      email: 'barbara.rangel1@example.com',
      address: '30803 Dean Neck, Bethbury, AR 56360',
      notes: 'Agree next put American. Thousand public run job whom professor.',
      frequentlycontacted: true,
      role: 'subadmin',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'QmFyYmFyYVJhbmdlbDE=',
    },
    {
      id: 2,
      firstname: 'Amanda',
      lastname: 'Mitchell',
      image: 'user2',
      department: 'Sales',
      company: 'Shaw, Smith and Schneider',
      phone: '911-901-5432',
      email: 'amanda.mitchell2@example.com',
      address: '0663 Dunn Greens Apt. 459, Port Evanborough, TX 96521',
      notes: 'Four tell bar nation action bit sense.',
      frequentlycontacted: true,
      role: 'subadmin',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'QW1hbmRhTWl0Y2hlbGwy',
    },
    {
      id: 3,
      firstname: 'Kenneth',
      lastname: 'Rodriguez',
      image: 'user5',
      department: 'Product',
      company: 'Johnson-Harris',
      phone: '359-160-5517',
      email: 'kenneth.rodriguez3@example.com',
      address: '780 Rosario Land Apt. 384, Stewartport, OK 35903',
      notes: 'Memory assume picture upon hotel present eat.',
      frequentlycontacted: true,
      role: 'designer',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'S2VubmV0aFJvZHJpZ3VlejM=',
    },
    {
      id: 4,
      firstname: 'Tanya',
      lastname: 'Thompson',
      image: 'user2',
      department: 'Engineering',
      company: 'Ibarra PLC',
      phone: '575-020-4645',
      email: 'tanya.thompson4@example.com',
      address: '6337 Krueger Viaduct, Juarezton, SD 49037',
      notes: 'Stand now ball person. Wear modern manager seem within character.',
      frequentlycontacted: true,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'VGFueWFUaG9tcHNvbjQ=',
    },
    {
      id: 5,
      firstname: 'Lisa',
      lastname: 'Wilson',
      image: 'user4',
      department: 'Engineering',
      company: 'Hill Inc',
      phone: '578-476-6583',
      email: 'lisa.wilson5@example.com',
      address: 'USCGC Williams, FPO AE 82398',
      notes: 'Real night bad concern wear fly. Deep whether energy join increase oil.',
      frequentlycontacted: false,
      role: 'staff',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'TGlzYVdpbHNvbjU=',
    },
    {
      id: 6,
      firstname: 'Kevin',
      lastname: 'Kramer',
      image: 'user4',
      department: 'HR',
      company: 'Pruitt Group',
      phone: '099-121-5112',
      email: 'kevin.kramer6@example.com',
      address: '802 Morse Fields, North Taylor, DC 49129',
      notes:
        'Source question book bring boy air perform. My behind billion significant goal item way.',
      frequentlycontacted: true,
      role: 'staff',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'S2V2aW5LcmFtZXI2',
    },
    {
      id: 7,
      firstname: 'Madison',
      lastname: 'Hogan',
      image: 'user3',
      department: 'Design',
      company: 'Martin-Cantrell',
      phone: '760-769-9259',
      email: 'madison.hogan7@example.com',
      address: '71730 Mayer Harbors, East Johnville, VA 22340',
      notes: 'Trouble indeed great woman.',
      frequentlycontacted: true,
      role: 'designer',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'TWFkaXNvbkhvZ2FuNw==',
    },
    {
      id: 8,
      firstname: 'Jessica',
      lastname: 'Pierce',
      image: 'user5',
      department: 'Engineering',
      company: 'Adams, Campbell and Rangel',
      phone: '898-635-1280',
      email: 'jessica.pierce8@example.com',
      address: '16872 Hoffman Hill Suite 967, North Philipchester, WV 03571',
      notes: 'Unit time outside road method wait.',
      frequentlycontacted: true,
      role: 'ADMIN',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'SmVzc2ljYVBpZXJjZTg=',
    },
    {
      id: 9,
      firstname: 'Allison',
      lastname: 'Richards',
      image: 'user3',
      department: 'HR',
      company: 'Brown-Barron',
      phone: '530-449-3972',
      email: 'allison.richards9@example.com',
      address: '729 Galvan Summit Suite 028, West Mary, LA 94783',
      notes:
        'Factor ball security might including. Government themselves number yeah see begin necessary.',
      frequentlycontacted: true,
      role: 'staff',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'QWxsaXNvblJpY2hhcmRzOQ==',
    },
    {
      id: 10,
      firstname: 'Cynthia',
      lastname: 'Johnson',
      image: 'user4',
      department: 'Product',
      company: 'Davis and Sons',
      phone: '474-505-1100',
      email: 'cynthia.johnson10@example.com',
      address: '6529 Sanders Extensions, South Cynthiachester, DC 18945',
      notes: 'Sell almost race remember customer member benefit.',
      frequentlycontacted: false,
      role: 'staff',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'Q3ludGhpYUpvaG5zb24xMA==',
    },
    {
      id: 11,
      firstname: 'Megan',
      lastname: 'Dawson',
      image: 'user3',
      department: 'Engineering',
      company: 'Shepherd, Campos and Willis',
      phone: '682-587-9557',
      email: 'megan.dawson11@example.com',
      address: '9550 Dean Field Suite 727, Haneymouth, FL 66189',
      notes:
        'Miss three language improve want make first. Ball protect girl structure meeting kitchen.',
      frequentlycontacted: false,
      role: 'manager',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'TWVnYW5EYXdzb24xMQ==',
    },
    {
      id: 12,
      firstname: 'Derek',
      lastname: 'Newton',
      image: 'user1',
      department: 'Design',
      company: 'Case-Hernandez',
      phone: '741-702-8234',
      email: 'derek.newton12@example.com',
      address: '93126 Brandon Spring, Lake Ana, WI 92700',
      notes:
        'Player difficult reflect save home. Feeling continue meeting growth standard nice market.',
      frequentlycontacted: true,
      role: 'staff',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'RGVyZWtOZXd0b24xMg==',
    },
    {
      id: 13,
      firstname: 'Joe',
      lastname: 'Arias',
      image: 'user3',
      department: 'Sales',
      company: 'Schmidt Group',
      phone: '727-241-4406',
      email: 'joe.arias13@example.com',
      address: 'Unit 2430 Box 4278, DPO AA 29039',
      notes: 'Real over player Mr most she reality. It light direction.',
      frequentlycontacted: false,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'Sm9lQXJpYXMxMw==',
    },
    {
      id: 14,
      firstname: 'Heather',
      lastname: 'Wilkinson',
      image: 'user3',
      department: 'HR',
      company: 'Wood Inc',
      phone: '650-521-9814',
      email: 'heather.wilkinson14@example.com',
      address: '573 Ann Pines, New Teresastad, TX 18592',
      notes: 'Southern across top line up.',
      frequentlycontacted: true,
      role: 'subadmin',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'SGVhdGhlcldpbGtpbnNvbjE0',
    },
    {
      id: 15,
      firstname: 'Amanda',
      lastname: 'Evans',
      image: 'user2',
      department: 'Sales',
      company: 'Andrews-Thornton',
      phone: '996-923-5714',
      email: 'amanda.evans15@example.com',
      address: '19603 James Skyway, New Bradley, NV 01496',
      notes: 'Election use relate sometimes.',
      frequentlycontacted: false,
      role: 'staff',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'QW1hbmRhRXZhbnMxNQ==',
    },
    {
      id: 16,
      firstname: 'Ian',
      lastname: 'Petersen',
      image: 'user4',
      department: 'Engineering',
      company: 'Taylor, Tucker and Perry',
      phone: '353-602-4952',
      email: 'ian.petersen16@example.com',
      address: '394 Veronica Dam, Garciachester, ND 92674',
      notes: 'Everything expert road them party until.',
      frequentlycontacted: true,
      role: 'subadmin',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'SWFuUGV0ZXJzZW4xNg==',
    },
    {
      id: 17,
      firstname: 'Patricia',
      lastname: 'Moore',
      image: 'user3',
      department: 'Design',
      company: 'Carter, Thompson and Martinez',
      phone: '184-493-7055',
      email: 'patricia.moore17@example.com',
      address: 'Unit 7115 Box 8079, DPO AE 81183',
      notes: 'Sound possible hair writer.',
      frequentlycontacted: false,
      role: 'ADMIN',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'UGF0cmljaWFNb29yZTE3',
    },
    {
      id: 18,
      firstname: 'Holly',
      lastname: 'Sanchez',
      image: 'user3',
      department: 'HR',
      company: 'Stone, Walls and Gamble',
      phone: '089-948-7391',
      email: 'holly.sanchez18@example.com',
      address: '2029 Wilson Spring, Shawnhaven, RI 74475',
      notes: 'Gun serve ahead major season. May strategy value time cut market.',
      frequentlycontacted: false,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'SG9sbHlTYW5jaGV6MTg=',
    },
    {
      id: 19,
      firstname: 'Nicole',
      lastname: 'Lynch',
      image: 'user3',
      department: 'Sales',
      company: 'Jones, Hobbs and Skinner',
      phone: '507-007-1432',
      email: 'nicole.lynch19@example.com',
      address: '1192 Tracey Ways, West Angelabury, DC 24840',
      notes: 'Although know environmental dog. Be program center dream reason policy series.',
      frequentlycontacted: true,
      role: 'ADMIN',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'Tmljb2xlTHluY2gxOQ==',
    },
    {
      id: 20,
      firstname: 'Tina',
      lastname: 'Mendez',
      image: 'user3',
      department: 'Engineering',
      company: 'Guzman-Coleman',
      phone: '616-523-8212',
      email: 'tina.mendez20@example.com',
      address: '9499 Nielsen Plain, Port Charles, CO 05693',
      notes: 'Its arrive defense commercial war.',
      frequentlycontacted: true,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'VGluYU1lbmRlejIw',
    },
    {
      id: 21,
      firstname: 'Tammy',
      lastname: 'Bautista',
      image: 'user3',
      department: 'Engineering',
      company: 'Kaufman-Lopez',
      phone: '968-196-2212',
      email: 'tammy.bautista21@example.com',
      address: '1846 Matthew Turnpike Suite 949, North Michael, NM 92299',
      notes: 'Available issue under each.',
      frequentlycontacted: false,
      role: 'subadmin',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'VGFtbXlCYXV0aXN0YTIx',
    },
    {
      id: 22,
      firstname: 'Gerald',
      lastname: 'Ward',
      image: 'user4',
      department: 'HR',
      company: 'Walls-Mitchell',
      phone: '027-712-3130',
      email: 'gerald.ward22@example.com',
      address: '57802 Jennifer Canyon, Gregoryburgh, CT 62670',
      notes:
        'Stage type catch natural across. Necessary commercial take military technology although campaign part.',
      frequentlycontacted: false,
      role: 'designer',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'R2VyYWxkV2FyZDIy',
    },
    {
      id: 23,
      firstname: 'Lori',
      lastname: 'Woods',
      image: 'user4',
      department: 'Product',
      company: 'Smith, Morales and Stark',
      phone: '569-344-8250',
      email: 'lori.woods23@example.com',
      address: '12246 Jonathan Port Suite 563, Port Stephanie, SD 21085',
      notes: 'Stuff government interest watch let movement evidence.',
      frequentlycontacted: true,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'TG9yaVdvb2RzMjM=',
    },
    {
      id: 24,
      firstname: 'Erica',
      lastname: 'West',
      image: 'user2',
      department: 'Engineering',
      company: 'Anderson, Obrien and Murray',
      phone: '774-964-0731',
      email: 'erica.west24@example.com',
      address: '4460 Cross Harbors, North Amybury, MT 15439',
      notes: 'Result tough name attack age.',
      frequentlycontacted: true,
      role: 'ADMIN',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'RXJpY2FXZXN0MjQ=',
    },
    {
      id: 25,
      firstname: 'William',
      lastname: 'Perry',
      image: 'user4',
      department: 'Design',
      company: 'Cordova-Johnston',
      phone: '092-482-5941',
      email: 'william.perry25@example.com',
      address: '6847 Chad Corner Suite 214, Johnsonhaven, DC 46381',
      notes: 'Seat teach read become box community TV. Popular find writer both this.',
      frequentlycontacted: true,
      role: 'ADMIN',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'V2lsbGlhbVBlcnJ5MjU=',
    },
    {
      id: 26,
      firstname: 'Scott',
      lastname: 'Strong',
      image: 'user4',
      department: 'Design',
      company: 'Leon-Scott',
      phone: '686-953-7478',
      email: 'scott.strong26@example.com',
      address: '3895 Jeffrey Haven Apt. 470, Herringberg, AZ 72252',
      notes:
        'Return modern everyone coach him difficult generation. Of accept fine follow plan business effort.',
      frequentlycontacted: false,
      role: 'ADMIN',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'U2NvdHRTdHJvbmcyNg==',
    },
    {
      id: 27,
      firstname: 'Pamela',
      lastname: 'Nelson',
      image: 'user2',
      department: 'Engineering',
      company: 'Carney, Thomas and Peters',
      phone: '950-250-7471',
      email: 'pamela.nelson27@example.com',
      address: '492 April Viaduct, Phillipsmouth, NY 17753',
      notes: 'Up agency realize too. Health process wide public five subject tonight its.',
      frequentlycontacted: true,
      role: 'ADMIN',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'UGFtZWxhTmVsc29uMjc=',
    },
    {
      id: 28,
      firstname: 'Dawn',
      lastname: 'Brown',
      image: 'user2',
      department: 'Engineering',
      company: 'Stone-Glass',
      phone: '548-138-6724',
      email: 'dawn.brown28@example.com',
      address: '54003 Melissa Divide Apt. 747, Port Kristin, FL 31928',
      notes: 'Guy situation way. Indeed audience food live thus.',
      frequentlycontacted: false,
      role: 'manager',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'RGF3bkJyb3duMjg=',
    },
    {
      id: 29,
      firstname: 'Rebecca',
      lastname: 'King',
      image: 'user5',
      department: 'Support',
      company: 'Willis and Sons',
      phone: '679-995-8091',
      email: 'rebecca.king29@example.com',
      address: '495 Howard Burgs Apt. 041, New Patricia, TX 67111',
      notes: 'Relationship stage explain myself figure president main cause.',
      frequentlycontacted: true,
      role: 'staff',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'UmViZWNjYUtpbmcyOQ==',
    },
    {
      id: 30,
      firstname: 'Charles',
      lastname: 'Martin',
      image: 'user5',
      department: 'Product',
      company: 'Rasmussen Inc',
      phone: '736-063-7656',
      email: 'charles.martin30@example.com',
      address: '80171 Suarez Causeway, Brandtmouth, NC 60613',
      notes: 'Condition difficult should increase pay interesting ready.',
      frequentlycontacted: true,
      role: 'designer',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'Q2hhcmxlc01hcnRpbjMw',
    },
    {
      id: 31,
      firstname: 'Jose',
      lastname: 'Thomas',
      image: 'user4',
      department: 'Support',
      company: 'Beasley, Barnes and Richardson',
      phone: '067-610-9690',
      email: 'jose.thomas31@example.com',
      address: '710 Snyder Mall Apt. 648, North Benjaminmouth, MO 50075',
      notes: 'Family meeting factor would. Deal later quality age although.',
      frequentlycontacted: false,
      role: 'subadmin',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'Sm9zZVRob21hczMx',
    },
    {
      id: 32,
      firstname: 'Michael',
      lastname: 'Palmer',
      image: 'user3',
      department: 'Marketing',
      company: 'Patterson, Fowler and Kelly',
      phone: '933-471-4200',
      email: 'michael.palmer32@example.com',
      address: '81904 Richard Lock Suite 943, East Morganton, NM 63988',
      notes: 'Develop laugh toward community quickly.',
      frequentlycontacted: true,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'TWljaGFlbFBhbG1lcjMy',
    },
    {
      id: 33,
      firstname: 'Kathleen',
      lastname: 'Burke',
      image: 'user2',
      department: 'Product',
      company: 'Foster-George',
      phone: '904-433-8523',
      email: 'kathleen.burke33@example.com',
      address: '73628 Jacob Avenue Apt. 527, Russellview, AZ 24209',
      notes: 'Region seek image.',
      frequentlycontacted: false,
      role: 'ADMIN',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'S2F0aGxlZW5CdXJrZTMz',
    },
    {
      id: 34,
      firstname: 'Carla',
      lastname: 'Vega',
      image: 'user4',
      department: 'Sales',
      company: 'Yu-Richard',
      phone: '041-000-2985',
      email: 'carla.vega34@example.com',
      address: '80411 Novak Station, Kimberlyton, KS 19482',
      notes: 'President would decision month with news. Civil show social discuss.',
      frequentlycontacted: true,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'Q2FybGFWZWdhMzQ=',
    },
    {
      id: 35,
      firstname: 'Kathleen',
      lastname: 'Allen',
      image: 'user3',
      department: 'Design',
      company: 'Gordon-Carter',
      phone: '681-238-1768',
      email: 'kathleen.allen35@example.com',
      address: '125 Adams Pass Suite 650, Hallberg, GA 52802',
      notes: 'Record themselves size need.',
      frequentlycontacted: true,
      role: 'ADMIN',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'S2F0aGxlZW5BbGxlbjM1',
    },
    {
      id: 36,
      firstname: 'Miranda',
      lastname: 'Jordan',
      image: 'user2',
      department: 'Engineering',
      company: 'Martin PLC',
      phone: '425-982-6162',
      email: 'miranda.jordan36@example.com',
      address: '956 Williams Wells, Lake Scottberg, RI 71356',
      notes:
        'Hear bag cell experience someone try. Forward decade should city letter including base.',
      frequentlycontacted: true,
      role: 'manager',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'TWlyYW5kYUpvcmRhbjM2',
    },
    {
      id: 37,
      firstname: 'Bryan',
      lastname: 'Butler',
      image: 'user5',
      department: 'Design',
      company: 'Green LLC',
      phone: '181-259-2427',
      email: 'bryan.butler37@example.com',
      address: '271 Cox Station Suite 845, Lynchmouth, AK 13659',
      notes: 'Capital along summer by. Chance series at center.',
      frequentlycontacted: true,
      role: 'designer',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'QnJ5YW5CdXRsZXIzNw==',
    },
    {
      id: 38,
      firstname: 'Devon',
      lastname: 'Spencer',
      image: 'user2',
      department: 'Design',
      company: 'Gonzalez Ltd',
      phone: '513-058-6673',
      email: 'devon.spencer38@example.com',
      address: '02186 Silva Island Suite 580, North Angelahaven, NY 90143',
      notes: 'Reveal rest recent respond.',
      frequentlycontacted: false,
      role: 'ADMIN',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'RGV2b25TcGVuY2VyMzg=',
    },
    {
      id: 39,
      firstname: 'Danielle',
      lastname: 'Hicks',
      image: 'user5',
      department: 'Product',
      company: 'Hughes-Parker',
      phone: '966-640-2422',
      email: 'danielle.hicks39@example.com',
      address: '22438 Craig Fort, South Robert, DC 37596',
      notes: 'Soon next take expect. Themselves almost recent morning month thank.',
      frequentlycontacted: false,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'RGFuaWVsbGVIaWNrczM5',
    },
    {
      id: 40,
      firstname: 'David',
      lastname: 'Ortiz',
      image: 'user4',
      department: 'Support',
      company: 'Williams, Salas and Macdonald',
      phone: '954-466-5655',
      email: 'david.ortiz40@example.com',
      address: '4296 Scott Mountain Suite 521, North Rickeyside, NE 29851',
      notes: 'Its research participant in language majority share. Along respond heavy year.',
      frequentlycontacted: true,
      role: 'staff',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'RGF2aWRPcnRpejQw',
    },
    {
      id: 41,
      firstname: 'Brittany',
      lastname: 'Wood',
      image: 'user1',
      department: 'HR',
      company: 'Walsh-Gross',
      phone: '748-105-0707',
      email: 'brittany.wood41@example.com',
      address: '0966 Collins Divide Apt. 553, Bonillafurt, KY 31235',
      notes: 'Book level professional professor do. Necessary task federal political.',
      frequentlycontacted: false,
      role: 'designer',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'QnJpdHRhbnlXb29kNDE=',
    },
    {
      id: 42,
      firstname: 'Peter',
      lastname: 'Mooney',
      image: 'user5',
      department: 'Support',
      company: 'Rivas, Forbes and Ho',
      phone: '026-212-4438',
      email: 'peter.mooney42@example.com',
      address: '73786 Roth Course Apt. 043, New Christopherhaven, DE 71412',
      notes: 'Accept modern interest last training. Able specific series today guy medical media.',
      frequentlycontacted: false,
      role: 'subadmin',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'UGV0ZXJNb29uZXk0Mg==',
    },
    {
      id: 43,
      firstname: 'Willie',
      lastname: 'Garrett',
      image: 'user4',
      department: 'Support',
      company: 'Sloan, Summers and Bishop',
      phone: '292-126-7420',
      email: 'willie.garrett43@example.com',
      address: '4754 Perez Creek, Coleberg, DE 31642',
      notes: 'Cost born action present pull series.',
      frequentlycontacted: true,
      role: 'staff',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'V2lsbGllR2FycmV0dDQz',
    },
    {
      id: 44,
      firstname: 'Tanner',
      lastname: 'Hernandez',
      image: 'user5',
      department: 'Marketing',
      company: 'Brown Ltd',
      phone: '132-085-2976',
      email: 'tanner.hernandez44@example.com',
      address: '9393 James Glen Suite 066, Ellenview, WA 22113',
      notes: 'Interview we best scientist method. Song grow speak much rule.',
      frequentlycontacted: true,
      role: 'manager',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'VGFubmVySGVybmFuZGV6NDQ=',
    },
    {
      id: 45,
      firstname: 'Jodi',
      lastname: 'Duncan',
      image: 'user2',
      department: 'Support',
      company: 'Scott, Rodriguez and Ashley',
      phone: '455-941-0041',
      email: 'jodi.duncan45@example.com',
      address: '64586 Nielsen Stravenue Suite 711, Johnsonberg, DE 29041',
      notes: 'Law house risk occur bring message of whose. Eat argue suddenly education fill door.',
      frequentlycontacted: true,
      role: 'staff',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'Sm9kaUR1bmNhbjQ1',
    },
    {
      id: 46,
      firstname: 'Emily',
      lastname: 'Bass',
      image: 'user5',
      department: 'Marketing',
      company: 'Gomez Group',
      phone: '289-261-9722',
      email: 'emily.bass46@example.com',
      address: '9181 Garcia Skyway, Mcclureburgh, IL 81005',
      notes: 'Clearly Mr everyone nice yard according various outside.',
      frequentlycontacted: true,
      role: 'subadmin',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'RW1pbHlCYXNzNDY=',
    },
    {
      id: 47,
      firstname: 'Pamela',
      lastname: 'Peterson',
      image: 'user4',
      department: 'Engineering',
      company: 'Martin-Schroeder',
      phone: '629-634-7000',
      email: 'pamela.peterson47@example.com',
      address: '458 Baker Stravenue Apt. 157, Shafferside, NY 23239',
      notes: 'Yes probably most great.',
      frequentlycontacted: false,
      role: 'subadmin',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'UGFtZWxhUGV0ZXJzb240Nw==',
    },
    {
      id: 48,
      firstname: 'Kenneth',
      lastname: 'Wright',
      image: 'user3',
      department: 'HR',
      company: 'Tran Inc',
      phone: '754-308-5106',
      email: 'kenneth.wright48@example.com',
      address: '2995 Lisa Greens, New Kyle, ID 95577',
      notes: 'Cost common to seek whole. Let nothing green.',
      frequentlycontacted: false,
      role: 'manager',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'S2VubmV0aFdyaWdodDQ4',
    },
    {
      id: 49,
      firstname: 'Michael',
      lastname: 'Reynolds',
      image: 'user4',
      department: 'Sales',
      company: 'Cohen-Jones',
      phone: '971-066-1059',
      email: 'michael.reynolds49@example.com',
      address: '4196 Nguyen Brooks Apt. 559, Kimberlyton, OR 21240',
      notes: 'Along you head agreement all.',
      frequentlycontacted: false,
      role: 'staff',
      starred: false,
      deleted: false,
      password: '123456',
      token: 'TWljaGFlbFJleW5vbGRzNDk=',
    },
    {
      id: 50,
      firstname: 'Elizabeth',
      lastname: 'Harvey',
      image: 'user1',
      department: 'Support',
      company: 'Rivera, Johnson and Hart',
      phone: '090-435-7014',
      email: 'elizabeth.harvey50@example.com',
      address: 'USCGC Griffin, FPO AA 74195',
      notes: 'May take lose thing.',
      frequentlycontacted: false,
      role: 'subadmin',
      starred: true,
      deleted: false,
      password: '123456',
      token: 'RWxpemFiZXRoSGFydmV5NTA=',
    },
  ],
  contactContent: 1,
  contactSearch: '',
  editContact: false,
  currentFilter: 'show_all',
};

export const ContactSlice = createSlice({
  name: 'contacts',
  initialState,
  reducers: {
    getContacts: (state: StateType, action) => {
      state.contacts = action.payload;
    },
    SearchContact: (state: StateType, action) => {
      state.contactSearch = action.payload;
    },
    SelectContact: (state: StateType, action) => {
      state.contactContent = action.payload;
    },
    DeleteContact: (state: StateType, action) => {
      state.contacts = state.contacts.map((contact) =>
        contact.id === action.payload ? { ...contact, deleted: !contact.deleted } : contact,
      );
    },
    toggleStarredContact: (state: StateType, action) => {
      state.contacts = state.contacts.map((contact) =>
        contact.id === action.payload ? { ...contact, starred: !contact.starred } : contact,
      );
    },
    isEdit: (state: StateType) => {
      state.editContact = !state.editContact;
    },
    setVisibilityFilter: (state: StateType, action) => {
      state.currentFilter = action.payload;
    },

    UpdateContact: {
      reducer: (state: StateType, action: PayloadAction<any>) => {
        state.contacts = state.contacts.map((contact) =>
          contact.id === action.payload.id
            ? { ...contact, [action.payload.field]: action.payload.value }
            : contact,
        );
      },
      prepare: (id, field, value) => {
        return {
          payload: { id, field, value },
        };
      },
    },
    addContact: {
      reducer: (state, action: PayloadAction<any>) => {
        state.contacts = [...state.contacts, action.payload];
      },
      prepare: (
        id,
        firstname,
        lastname,
        image,
        department,
        company,
        phone,
        email,
        address,
        notes,
        role,
        password,
        token,
      ) => {
        return {
          payload: {
            id,
            firstname,
            lastname,
            image,
            department,
            company,
            phone,
            email,
            address,
            notes,
            frequentlycontacted: false,
            starred: false,
            deleted: false,
            role,
            password,
            token,
          },
        };
      },
    },
  },
});

export const {
  getContacts,
  SearchContact,
  isEdit,
  SelectContact,
  DeleteContact,
  toggleStarredContact,
  UpdateContact,
  addContact,
  setVisibilityFilter,
} = ContactSlice.actions;

export const fetchContacts = () => async (dispatch: AppDispatch) => {
  try {
    const response = await axios.get(`${API_URL}`);
    dispatch(getContacts(response.data));
  } catch (err: any) {
    throw new Error(err);
  }
};

export default ContactSlice.reducer;
